// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "public.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Cmd {

namespace {

const ::google::protobuf::EnumDescriptor* enCmdId_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_public_2eproto() {
  protobuf_AddDesc_public_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "public.proto");
  GOOGLE_CHECK(file != NULL);
  enCmdId_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_public_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_public_2eproto() {
}

void protobuf_AddDesc_public_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014public.proto\022\003Cmd*\305\001\n\007enCmdId\022\n\n\006enNon"
    "e\020\000\022\025\n\021enNotifyLogicInfo\020\001\022\013\n\007enLogin\020\002\022"
    "\027\n\023enRequestCreateRoom\020\003\022\030\n\024enReturnCrea"
    "teResult\020\004\022\026\n\022enRequestEnterRoom\020\005\022\027\n\023en"
    "ReturnEnterResult\020\006\022\017\n\013enVoiceData\020\007\022\025\n\021"
    "enNotifyLeaveRoom\020\010", 219);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "public.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_public_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_public_2eproto {
  StaticDescriptorInitializer_public_2eproto() {
    protobuf_AddDesc_public_2eproto();
  }
} static_descriptor_initializer_public_2eproto_;

const ::google::protobuf::EnumDescriptor* enCmdId_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return enCmdId_descriptor_;
}
bool enCmdId_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Cmd

// @@protoc_insertion_point(global_scope)
