// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: public.proto

#ifndef PROTOBUF_public_2eproto__INCLUDED
#define PROTOBUF_public_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace Cmd {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_public_2eproto();
void protobuf_AssignDesc_public_2eproto();
void protobuf_ShutdownFile_public_2eproto();


enum enCmdId {
  enNone = 0,
  enNotifyLogicInfo = 1,
  enLogin = 2,
  enRequestCreateRoom = 3,
  enReturnCreateResult = 4,
  enRequestEnterRoom = 5,
  enReturnEnterResult = 6,
  enVoiceData = 7,
  enNotifyLeaveRoom = 8
};
bool enCmdId_IsValid(int value);
const enCmdId enCmdId_MIN = enNone;
const enCmdId enCmdId_MAX = enNotifyLeaveRoom;
const int enCmdId_ARRAYSIZE = enCmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* enCmdId_descriptor();
inline const ::std::string& enCmdId_Name(enCmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    enCmdId_descriptor(), value);
}
inline bool enCmdId_Parse(
    const ::std::string& name, enCmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<enCmdId>(
    enCmdId_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace Cmd

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< Cmd::enCmdId>() {
  return Cmd::enCmdId_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_public_2eproto__INCLUDED
