// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: public.proto

package Cmd;

public final class Public {
  private Public() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code Cmd.enRoomType}
   *
   * <pre>
   *&#47; 房间类型
   * </pre>
   */
  public enum enRoomType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ROOM_TYPE_MIN = 0;</code>
     */
    ROOM_TYPE_MIN(0, 0),
    /**
     * <code>ROOM_TYPE_QUEUE = 1;</code>
     *
     * <pre>
     *&#47; 单人队列排麦模式(只能一个人拿麦)
     * </pre>
     */
    ROOM_TYPE_QUEUE(1, 1),
    /**
     * <code>ROOM_TYPE_FREE = 2;</code>
     *
     * <pre>
     *&#47; 自由模式(最多4个人)
     * </pre>
     */
    ROOM_TYPE_FREE(2, 2),
    /**
     * <code>ROOM_TYPE_TWO = 3;</code>
     *
     * <pre>
     *&#47; 二人模式
     * </pre>
     */
    ROOM_TYPE_TWO(3, 3),
    /**
     * <code>ROOM_TYPE_ONLY = 4;</code>
     *
     * <pre>
     *&#47; 抢麦模式
     * </pre>
     */
    ROOM_TYPE_ONLY(4, 4),
    /**
     * <code>ROOM_TYPE_MAX = 5;</code>
     */
    ROOM_TYPE_MAX(5, 5),
    ;

    /**
     * <code>ROOM_TYPE_MIN = 0;</code>
     */
    public static final int ROOM_TYPE_MIN_VALUE = 0;
    /**
     * <code>ROOM_TYPE_QUEUE = 1;</code>
     *
     * <pre>
     *&#47; 单人队列排麦模式(只能一个人拿麦)
     * </pre>
     */
    public static final int ROOM_TYPE_QUEUE_VALUE = 1;
    /**
     * <code>ROOM_TYPE_FREE = 2;</code>
     *
     * <pre>
     *&#47; 自由模式(最多4个人)
     * </pre>
     */
    public static final int ROOM_TYPE_FREE_VALUE = 2;
    /**
     * <code>ROOM_TYPE_TWO = 3;</code>
     *
     * <pre>
     *&#47; 二人模式
     * </pre>
     */
    public static final int ROOM_TYPE_TWO_VALUE = 3;
    /**
     * <code>ROOM_TYPE_ONLY = 4;</code>
     *
     * <pre>
     *&#47; 抢麦模式
     * </pre>
     */
    public static final int ROOM_TYPE_ONLY_VALUE = 4;
    /**
     * <code>ROOM_TYPE_MAX = 5;</code>
     */
    public static final int ROOM_TYPE_MAX_VALUE = 5;


    public final int getNumber() { return value; }

    public static enRoomType valueOf(int value) {
      switch (value) {
        case 0: return ROOM_TYPE_MIN;
        case 1: return ROOM_TYPE_QUEUE;
        case 2: return ROOM_TYPE_FREE;
        case 3: return ROOM_TYPE_TWO;
        case 4: return ROOM_TYPE_ONLY;
        case 5: return ROOM_TYPE_MAX;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<enRoomType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<enRoomType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<enRoomType>() {
            public enRoomType findValueByNumber(int number) {
              return enRoomType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Cmd.Public.getDescriptor().getEnumTypes().get(0);
    }

    private static final enRoomType[] VALUES = values();

    public static enRoomType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private enRoomType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Cmd.enRoomType)
  }

  /**
   * Protobuf enum {@code Cmd.enRoomReason}
   *
   * <pre>
   *&#47; 创建房间的理由
   * </pre>
   */
  public enum enRoomReason
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ROOM_REASON_MIN = 0;</code>
     */
    ROOM_REASON_MIN(0, 0),
    /**
     * <code>ROOM_REASON_NORMAL = 1;</code>
     */
    ROOM_REASON_NORMAL(1, 1),
    /**
     * <code>ROOM_REASON_RANDCHAT = 2;</code>
     */
    ROOM_REASON_RANDCHAT(2, 2),
    /**
     * <code>ROOM_REASON_MAX = 3;</code>
     */
    ROOM_REASON_MAX(3, 3),
    ;

    /**
     * <code>ROOM_REASON_MIN = 0;</code>
     */
    public static final int ROOM_REASON_MIN_VALUE = 0;
    /**
     * <code>ROOM_REASON_NORMAL = 1;</code>
     */
    public static final int ROOM_REASON_NORMAL_VALUE = 1;
    /**
     * <code>ROOM_REASON_RANDCHAT = 2;</code>
     */
    public static final int ROOM_REASON_RANDCHAT_VALUE = 2;
    /**
     * <code>ROOM_REASON_MAX = 3;</code>
     */
    public static final int ROOM_REASON_MAX_VALUE = 3;


    public final int getNumber() { return value; }

    public static enRoomReason valueOf(int value) {
      switch (value) {
        case 0: return ROOM_REASON_MIN;
        case 1: return ROOM_REASON_NORMAL;
        case 2: return ROOM_REASON_RANDCHAT;
        case 3: return ROOM_REASON_MAX;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<enRoomReason>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<enRoomReason>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<enRoomReason>() {
            public enRoomReason findValueByNumber(int number) {
              return enRoomReason.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Cmd.Public.getDescriptor().getEnumTypes().get(1);
    }

    private static final enRoomReason[] VALUES = values();

    public static enRoomReason valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private enRoomReason(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Cmd.enRoomReason)
  }

  /**
   * Protobuf enum {@code Cmd.enCmdId}
   */
  public enum enCmdId
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>enNone = 0;</code>
     */
    enNone(0, 0),
    /**
     * <code>enRequestLogicInfo = 1;</code>
     *
     * <pre>
     *&#47; 请求逻辑服务器信息
     * </pre>
     */
    enRequestLogicInfo(1, 1),
    /**
     * <code>enNotifyLogicInfo = 2;</code>
     *
     * <pre>
     *&#47; 返回需要连接的逻辑服务器信息
     * </pre>
     */
    enNotifyLogicInfo(2, 2),
    /**
     * <code>enRequestLogin = 3;</code>
     *
     * <pre>
     *&#47; 请求登录
     * </pre>
     */
    enRequestLogin(3, 3),
    /**
     * <code>enNotifyLoginResult = 4;</code>
     *
     * <pre>
     *&#47; 返回登录结果 
     * </pre>
     */
    enNotifyLoginResult(4, 4),
    /**
     * <code>enRequestCreateRoom = 5;</code>
     *
     * <pre>
     *&#47; 创建房间
     * </pre>
     */
    enRequestCreateRoom(5, 5),
    /**
     * <code>enNotifyCreateResult = 6;</code>
     *
     * <pre>
     *&#47; 创建房间返回
     * </pre>
     */
    enNotifyCreateResult(6, 6),
    /**
     * <code>enRequestEnterRoom = 7;</code>
     *
     * <pre>
     *&#47; 加入房间
     * </pre>
     */
    enRequestEnterRoom(7, 7),
    /**
     * <code>enNotifyEnterResult = 8;</code>
     *
     * <pre>
     *&#47; 加入房间返回
     * </pre>
     */
    enNotifyEnterResult(8, 8),
    /**
     * <code>enRequestRoomList = 9;</code>
     *
     * <pre>
     *&#47; 申请房间列表
     * </pre>
     */
    enRequestRoomList(9, 9),
    /**
     * <code>enNotifyRoomList = 10;</code>
     *
     * <pre>
     *&#47; 返回房间列表
     * </pre>
     */
    enNotifyRoomList(10, 10),
    /**
     * <code>enNotifyAddVoiceUser = 11;</code>
     *
     * <pre>
     *&#47; 增加收听通道
     * </pre>
     */
    enNotifyAddVoiceUser(11, 11),
    /**
     * <code>enRequestJoinMicQueue = 12;</code>
     *
     * <pre>
     *&#47; 加入麦序
     * </pre>
     */
    enRequestJoinMicQueue(12, 12),
    /**
     * <code>enRequestLeaveMicQueue = 13;</code>
     *
     * <pre>
     *&#47; 离开麦序
     * </pre>
     */
    enRequestLeaveMicQueue(13, 13),
    /**
     * <code>enNotifyMicQueue = 14;</code>
     *
     * <pre>
     *&#47; 返回麦序
     * </pre>
     */
    enNotifyMicQueue(14, 14),
    /**
     * <code>enNotifyTakeMic = 15;</code>
     *
     * <pre>
     *&#47; 到某人聊天了
     * </pre>
     */
    enNotifyTakeMic(15, 15),
    /**
     * <code>enRequestLeaveRoom = 16;</code>
     *
     * <pre>
     *&#47; 离开房间
     * </pre>
     */
    enRequestLeaveRoom(16, 16),
    /**
     * <code>enNotifyDelVoiceUser = 17;</code>
     *
     * <pre>
     *&#47; 删除一个通道
     * </pre>
     */
    enNotifyDelVoiceUser(17, 17),
    /**
     * <code>enNotifySomeEnterRoom = 18;</code>
     *
     * <pre>
     *&#47; 通知有人进入房间
     * </pre>
     */
    enNotifySomeEnterRoom(18, 18),
    /**
     * <code>enNotifyRandChat = 21;</code>
     *
     * <pre>
     *&#47; 有人想和你随机聊天
     * </pre>
     */
    enNotifyRandChat(19, 21),
    /**
     * <code>enReturnRandChat = 22;</code>
     *
     * <pre>
     *&#47; 返回是否要随机聊天
     * </pre>
     */
    enReturnRandChat(20, 22),
    /**
     * <code>enNotifySomeLeaveRoom = 19;</code>
     *
     * <pre>
     *&#47; 有人离开房间
     * </pre>
     */
    enNotifySomeLeaveRoom(21, 19),
    ;

    /**
     * <code>enNone = 0;</code>
     */
    public static final int enNone_VALUE = 0;
    /**
     * <code>enRequestLogicInfo = 1;</code>
     *
     * <pre>
     *&#47; 请求逻辑服务器信息
     * </pre>
     */
    public static final int enRequestLogicInfo_VALUE = 1;
    /**
     * <code>enNotifyLogicInfo = 2;</code>
     *
     * <pre>
     *&#47; 返回需要连接的逻辑服务器信息
     * </pre>
     */
    public static final int enNotifyLogicInfo_VALUE = 2;
    /**
     * <code>enRequestLogin = 3;</code>
     *
     * <pre>
     *&#47; 请求登录
     * </pre>
     */
    public static final int enRequestLogin_VALUE = 3;
    /**
     * <code>enNotifyLoginResult = 4;</code>
     *
     * <pre>
     *&#47; 返回登录结果 
     * </pre>
     */
    public static final int enNotifyLoginResult_VALUE = 4;
    /**
     * <code>enRequestCreateRoom = 5;</code>
     *
     * <pre>
     *&#47; 创建房间
     * </pre>
     */
    public static final int enRequestCreateRoom_VALUE = 5;
    /**
     * <code>enNotifyCreateResult = 6;</code>
     *
     * <pre>
     *&#47; 创建房间返回
     * </pre>
     */
    public static final int enNotifyCreateResult_VALUE = 6;
    /**
     * <code>enRequestEnterRoom = 7;</code>
     *
     * <pre>
     *&#47; 加入房间
     * </pre>
     */
    public static final int enRequestEnterRoom_VALUE = 7;
    /**
     * <code>enNotifyEnterResult = 8;</code>
     *
     * <pre>
     *&#47; 加入房间返回
     * </pre>
     */
    public static final int enNotifyEnterResult_VALUE = 8;
    /**
     * <code>enRequestRoomList = 9;</code>
     *
     * <pre>
     *&#47; 申请房间列表
     * </pre>
     */
    public static final int enRequestRoomList_VALUE = 9;
    /**
     * <code>enNotifyRoomList = 10;</code>
     *
     * <pre>
     *&#47; 返回房间列表
     * </pre>
     */
    public static final int enNotifyRoomList_VALUE = 10;
    /**
     * <code>enNotifyAddVoiceUser = 11;</code>
     *
     * <pre>
     *&#47; 增加收听通道
     * </pre>
     */
    public static final int enNotifyAddVoiceUser_VALUE = 11;
    /**
     * <code>enRequestJoinMicQueue = 12;</code>
     *
     * <pre>
     *&#47; 加入麦序
     * </pre>
     */
    public static final int enRequestJoinMicQueue_VALUE = 12;
    /**
     * <code>enRequestLeaveMicQueue = 13;</code>
     *
     * <pre>
     *&#47; 离开麦序
     * </pre>
     */
    public static final int enRequestLeaveMicQueue_VALUE = 13;
    /**
     * <code>enNotifyMicQueue = 14;</code>
     *
     * <pre>
     *&#47; 返回麦序
     * </pre>
     */
    public static final int enNotifyMicQueue_VALUE = 14;
    /**
     * <code>enNotifyTakeMic = 15;</code>
     *
     * <pre>
     *&#47; 到某人聊天了
     * </pre>
     */
    public static final int enNotifyTakeMic_VALUE = 15;
    /**
     * <code>enRequestLeaveRoom = 16;</code>
     *
     * <pre>
     *&#47; 离开房间
     * </pre>
     */
    public static final int enRequestLeaveRoom_VALUE = 16;
    /**
     * <code>enNotifyDelVoiceUser = 17;</code>
     *
     * <pre>
     *&#47; 删除一个通道
     * </pre>
     */
    public static final int enNotifyDelVoiceUser_VALUE = 17;
    /**
     * <code>enNotifySomeEnterRoom = 18;</code>
     *
     * <pre>
     *&#47; 通知有人进入房间
     * </pre>
     */
    public static final int enNotifySomeEnterRoom_VALUE = 18;
    /**
     * <code>enNotifyRandChat = 21;</code>
     *
     * <pre>
     *&#47; 有人想和你随机聊天
     * </pre>
     */
    public static final int enNotifyRandChat_VALUE = 21;
    /**
     * <code>enReturnRandChat = 22;</code>
     *
     * <pre>
     *&#47; 返回是否要随机聊天
     * </pre>
     */
    public static final int enReturnRandChat_VALUE = 22;
    /**
     * <code>enNotifySomeLeaveRoom = 19;</code>
     *
     * <pre>
     *&#47; 有人离开房间
     * </pre>
     */
    public static final int enNotifySomeLeaveRoom_VALUE = 19;


    public final int getNumber() { return value; }

    public static enCmdId valueOf(int value) {
      switch (value) {
        case 0: return enNone;
        case 1: return enRequestLogicInfo;
        case 2: return enNotifyLogicInfo;
        case 3: return enRequestLogin;
        case 4: return enNotifyLoginResult;
        case 5: return enRequestCreateRoom;
        case 6: return enNotifyCreateResult;
        case 7: return enRequestEnterRoom;
        case 8: return enNotifyEnterResult;
        case 9: return enRequestRoomList;
        case 10: return enNotifyRoomList;
        case 11: return enNotifyAddVoiceUser;
        case 12: return enRequestJoinMicQueue;
        case 13: return enRequestLeaveMicQueue;
        case 14: return enNotifyMicQueue;
        case 15: return enNotifyTakeMic;
        case 16: return enRequestLeaveRoom;
        case 17: return enNotifyDelVoiceUser;
        case 18: return enNotifySomeEnterRoom;
        case 21: return enNotifyRandChat;
        case 22: return enReturnRandChat;
        case 19: return enNotifySomeLeaveRoom;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<enCmdId>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<enCmdId>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<enCmdId>() {
            public enCmdId findValueByNumber(int number) {
              return enCmdId.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Cmd.Public.getDescriptor().getEnumTypes().get(2);
    }

    private static final enCmdId[] VALUES = values();

    public static enCmdId valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private enCmdId(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Cmd.enCmdId)
  }

  public interface stRoomInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint64 roomid = 1;
    /**
     * <code>required uint64 roomid = 1;</code>
     */
    boolean hasRoomid();
    /**
     * <code>required uint64 roomid = 1;</code>
     */
    long getRoomid();

    // required .Cmd.enRoomType roomtype = 2;
    /**
     * <code>required .Cmd.enRoomType roomtype = 2;</code>
     */
    boolean hasRoomtype();
    /**
     * <code>required .Cmd.enRoomType roomtype = 2;</code>
     */
    Cmd.Public.enRoomType getRoomtype();

    // required uint32 num = 3;
    /**
     * <code>required uint32 num = 3;</code>
     */
    boolean hasNum();
    /**
     * <code>required uint32 num = 3;</code>
     */
    int getNum();
  }
  /**
   * Protobuf type {@code Cmd.stRoomInfo}
   *
   * <pre>
   *&#47; 房间信息
   * </pre>
   */
  public static final class stRoomInfo extends
      com.google.protobuf.GeneratedMessage
      implements stRoomInfoOrBuilder {
    // Use stRoomInfo.newBuilder() to construct.
    private stRoomInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private stRoomInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final stRoomInfo defaultInstance;
    public static stRoomInfo getDefaultInstance() {
      return defaultInstance;
    }

    public stRoomInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private stRoomInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              roomid_ = input.readUInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              Cmd.Public.enRoomType value = Cmd.Public.enRoomType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                roomtype_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              num_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Cmd.Public.internal_static_Cmd_stRoomInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Cmd.Public.internal_static_Cmd_stRoomInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Cmd.Public.stRoomInfo.class, Cmd.Public.stRoomInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<stRoomInfo> PARSER =
        new com.google.protobuf.AbstractParser<stRoomInfo>() {
      public stRoomInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new stRoomInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<stRoomInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint64 roomid = 1;
    public static final int ROOMID_FIELD_NUMBER = 1;
    private long roomid_;
    /**
     * <code>required uint64 roomid = 1;</code>
     */
    public boolean hasRoomid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 roomid = 1;</code>
     */
    public long getRoomid() {
      return roomid_;
    }

    // required .Cmd.enRoomType roomtype = 2;
    public static final int ROOMTYPE_FIELD_NUMBER = 2;
    private Cmd.Public.enRoomType roomtype_;
    /**
     * <code>required .Cmd.enRoomType roomtype = 2;</code>
     */
    public boolean hasRoomtype() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .Cmd.enRoomType roomtype = 2;</code>
     */
    public Cmd.Public.enRoomType getRoomtype() {
      return roomtype_;
    }

    // required uint32 num = 3;
    public static final int NUM_FIELD_NUMBER = 3;
    private int num_;
    /**
     * <code>required uint32 num = 3;</code>
     */
    public boolean hasNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 num = 3;</code>
     */
    public int getNum() {
      return num_;
    }

    private void initFields() {
      roomid_ = 0L;
      roomtype_ = Cmd.Public.enRoomType.ROOM_TYPE_MIN;
      num_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRoomid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRoomtype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, roomid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, roomtype_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, num_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, roomid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, roomtype_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, num_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Cmd.Public.stRoomInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cmd.Public.stRoomInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cmd.Public.stRoomInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cmd.Public.stRoomInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cmd.Public.stRoomInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Cmd.Public.stRoomInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Cmd.Public.stRoomInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Cmd.Public.stRoomInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Cmd.Public.stRoomInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Cmd.Public.stRoomInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Cmd.Public.stRoomInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Cmd.stRoomInfo}
     *
     * <pre>
     *&#47; 房间信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Cmd.Public.stRoomInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Cmd.Public.internal_static_Cmd_stRoomInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Cmd.Public.internal_static_Cmd_stRoomInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Cmd.Public.stRoomInfo.class, Cmd.Public.stRoomInfo.Builder.class);
      }

      // Construct using Cmd.Public.stRoomInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        roomid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        roomtype_ = Cmd.Public.enRoomType.ROOM_TYPE_MIN;
        bitField0_ = (bitField0_ & ~0x00000002);
        num_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Cmd.Public.internal_static_Cmd_stRoomInfo_descriptor;
      }

      public Cmd.Public.stRoomInfo getDefaultInstanceForType() {
        return Cmd.Public.stRoomInfo.getDefaultInstance();
      }

      public Cmd.Public.stRoomInfo build() {
        Cmd.Public.stRoomInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Cmd.Public.stRoomInfo buildPartial() {
        Cmd.Public.stRoomInfo result = new Cmd.Public.stRoomInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roomid_ = roomid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.roomtype_ = roomtype_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.num_ = num_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Cmd.Public.stRoomInfo) {
          return mergeFrom((Cmd.Public.stRoomInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Cmd.Public.stRoomInfo other) {
        if (other == Cmd.Public.stRoomInfo.getDefaultInstance()) return this;
        if (other.hasRoomid()) {
          setRoomid(other.getRoomid());
        }
        if (other.hasRoomtype()) {
          setRoomtype(other.getRoomtype());
        }
        if (other.hasNum()) {
          setNum(other.getNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRoomid()) {
          
          return false;
        }
        if (!hasRoomtype()) {
          
          return false;
        }
        if (!hasNum()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Cmd.Public.stRoomInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Cmd.Public.stRoomInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint64 roomid = 1;
      private long roomid_ ;
      /**
       * <code>required uint64 roomid = 1;</code>
       */
      public boolean hasRoomid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 roomid = 1;</code>
       */
      public long getRoomid() {
        return roomid_;
      }
      /**
       * <code>required uint64 roomid = 1;</code>
       */
      public Builder setRoomid(long value) {
        bitField0_ |= 0x00000001;
        roomid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 roomid = 1;</code>
       */
      public Builder clearRoomid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roomid_ = 0L;
        onChanged();
        return this;
      }

      // required .Cmd.enRoomType roomtype = 2;
      private Cmd.Public.enRoomType roomtype_ = Cmd.Public.enRoomType.ROOM_TYPE_MIN;
      /**
       * <code>required .Cmd.enRoomType roomtype = 2;</code>
       */
      public boolean hasRoomtype() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .Cmd.enRoomType roomtype = 2;</code>
       */
      public Cmd.Public.enRoomType getRoomtype() {
        return roomtype_;
      }
      /**
       * <code>required .Cmd.enRoomType roomtype = 2;</code>
       */
      public Builder setRoomtype(Cmd.Public.enRoomType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        roomtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Cmd.enRoomType roomtype = 2;</code>
       */
      public Builder clearRoomtype() {
        bitField0_ = (bitField0_ & ~0x00000002);
        roomtype_ = Cmd.Public.enRoomType.ROOM_TYPE_MIN;
        onChanged();
        return this;
      }

      // required uint32 num = 3;
      private int num_ ;
      /**
       * <code>required uint32 num = 3;</code>
       */
      public boolean hasNum() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 num = 3;</code>
       */
      public int getNum() {
        return num_;
      }
      /**
       * <code>required uint32 num = 3;</code>
       */
      public Builder setNum(int value) {
        bitField0_ |= 0x00000004;
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 num = 3;</code>
       */
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        num_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Cmd.stRoomInfo)
    }

    static {
      defaultInstance = new stRoomInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Cmd.stRoomInfo)
  }

  public interface stVoiceUserInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint64 id = 1;
    /**
     * <code>required uint64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint64 id = 1;</code>
     */
    long getId();
  }
  /**
   * Protobuf type {@code Cmd.stVoiceUserInfo}
   *
   * <pre>
   *&#47; 数据用户信息
   * </pre>
   */
  public static final class stVoiceUserInfo extends
      com.google.protobuf.GeneratedMessage
      implements stVoiceUserInfoOrBuilder {
    // Use stVoiceUserInfo.newBuilder() to construct.
    private stVoiceUserInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private stVoiceUserInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final stVoiceUserInfo defaultInstance;
    public static stVoiceUserInfo getDefaultInstance() {
      return defaultInstance;
    }

    public stVoiceUserInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private stVoiceUserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Cmd.Public.internal_static_Cmd_stVoiceUserInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Cmd.Public.internal_static_Cmd_stVoiceUserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Cmd.Public.stVoiceUserInfo.class, Cmd.Public.stVoiceUserInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<stVoiceUserInfo> PARSER =
        new com.google.protobuf.AbstractParser<stVoiceUserInfo>() {
      public stVoiceUserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new stVoiceUserInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<stVoiceUserInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required uint64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    private void initFields() {
      id_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Cmd.Public.stVoiceUserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cmd.Public.stVoiceUserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cmd.Public.stVoiceUserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cmd.Public.stVoiceUserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cmd.Public.stVoiceUserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Cmd.Public.stVoiceUserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Cmd.Public.stVoiceUserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Cmd.Public.stVoiceUserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Cmd.Public.stVoiceUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Cmd.Public.stVoiceUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Cmd.Public.stVoiceUserInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Cmd.stVoiceUserInfo}
     *
     * <pre>
     *&#47; 数据用户信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Cmd.Public.stVoiceUserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Cmd.Public.internal_static_Cmd_stVoiceUserInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Cmd.Public.internal_static_Cmd_stVoiceUserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Cmd.Public.stVoiceUserInfo.class, Cmd.Public.stVoiceUserInfo.Builder.class);
      }

      // Construct using Cmd.Public.stVoiceUserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Cmd.Public.internal_static_Cmd_stVoiceUserInfo_descriptor;
      }

      public Cmd.Public.stVoiceUserInfo getDefaultInstanceForType() {
        return Cmd.Public.stVoiceUserInfo.getDefaultInstance();
      }

      public Cmd.Public.stVoiceUserInfo build() {
        Cmd.Public.stVoiceUserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Cmd.Public.stVoiceUserInfo buildPartial() {
        Cmd.Public.stVoiceUserInfo result = new Cmd.Public.stVoiceUserInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Cmd.Public.stVoiceUserInfo) {
          return mergeFrom((Cmd.Public.stVoiceUserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Cmd.Public.stVoiceUserInfo other) {
        if (other == Cmd.Public.stVoiceUserInfo.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Cmd.Public.stVoiceUserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Cmd.Public.stVoiceUserInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint64 id = 1;
      private long id_ ;
      /**
       * <code>required uint64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Cmd.stVoiceUserInfo)
    }

    static {
      defaultInstance = new stVoiceUserInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Cmd.stVoiceUserInfo)
  }

  public interface stMicInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint64 tempid = 1;
    /**
     * <code>required uint64 tempid = 1;</code>
     */
    boolean hasTempid();
    /**
     * <code>required uint64 tempid = 1;</code>
     */
    long getTempid();

    // required string uniqueid = 2;
    /**
     * <code>required string uniqueid = 2;</code>
     */
    boolean hasUniqueid();
    /**
     * <code>required string uniqueid = 2;</code>
     */
    java.lang.String getUniqueid();
    /**
     * <code>required string uniqueid = 2;</code>
     */
    com.google.protobuf.ByteString
        getUniqueidBytes();
  }
  /**
   * Protobuf type {@code Cmd.stMicInfo}
   *
   * <pre>
   *&#47; 麦序信息
   * </pre>
   */
  public static final class stMicInfo extends
      com.google.protobuf.GeneratedMessage
      implements stMicInfoOrBuilder {
    // Use stMicInfo.newBuilder() to construct.
    private stMicInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private stMicInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final stMicInfo defaultInstance;
    public static stMicInfo getDefaultInstance() {
      return defaultInstance;
    }

    public stMicInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private stMicInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              tempid_ = input.readUInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              uniqueid_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Cmd.Public.internal_static_Cmd_stMicInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Cmd.Public.internal_static_Cmd_stMicInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Cmd.Public.stMicInfo.class, Cmd.Public.stMicInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<stMicInfo> PARSER =
        new com.google.protobuf.AbstractParser<stMicInfo>() {
      public stMicInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new stMicInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<stMicInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint64 tempid = 1;
    public static final int TEMPID_FIELD_NUMBER = 1;
    private long tempid_;
    /**
     * <code>required uint64 tempid = 1;</code>
     */
    public boolean hasTempid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 tempid = 1;</code>
     */
    public long getTempid() {
      return tempid_;
    }

    // required string uniqueid = 2;
    public static final int UNIQUEID_FIELD_NUMBER = 2;
    private java.lang.Object uniqueid_;
    /**
     * <code>required string uniqueid = 2;</code>
     */
    public boolean hasUniqueid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string uniqueid = 2;</code>
     */
    public java.lang.String getUniqueid() {
      java.lang.Object ref = uniqueid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uniqueid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string uniqueid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUniqueidBytes() {
      java.lang.Object ref = uniqueid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uniqueid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      tempid_ = 0L;
      uniqueid_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTempid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUniqueid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, tempid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUniqueidBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, tempid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUniqueidBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Cmd.Public.stMicInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cmd.Public.stMicInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cmd.Public.stMicInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cmd.Public.stMicInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cmd.Public.stMicInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Cmd.Public.stMicInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Cmd.Public.stMicInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Cmd.Public.stMicInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Cmd.Public.stMicInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Cmd.Public.stMicInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Cmd.Public.stMicInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Cmd.stMicInfo}
     *
     * <pre>
     *&#47; 麦序信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Cmd.Public.stMicInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Cmd.Public.internal_static_Cmd_stMicInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Cmd.Public.internal_static_Cmd_stMicInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Cmd.Public.stMicInfo.class, Cmd.Public.stMicInfo.Builder.class);
      }

      // Construct using Cmd.Public.stMicInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        tempid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        uniqueid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Cmd.Public.internal_static_Cmd_stMicInfo_descriptor;
      }

      public Cmd.Public.stMicInfo getDefaultInstanceForType() {
        return Cmd.Public.stMicInfo.getDefaultInstance();
      }

      public Cmd.Public.stMicInfo build() {
        Cmd.Public.stMicInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Cmd.Public.stMicInfo buildPartial() {
        Cmd.Public.stMicInfo result = new Cmd.Public.stMicInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tempid_ = tempid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uniqueid_ = uniqueid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Cmd.Public.stMicInfo) {
          return mergeFrom((Cmd.Public.stMicInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Cmd.Public.stMicInfo other) {
        if (other == Cmd.Public.stMicInfo.getDefaultInstance()) return this;
        if (other.hasTempid()) {
          setTempid(other.getTempid());
        }
        if (other.hasUniqueid()) {
          bitField0_ |= 0x00000002;
          uniqueid_ = other.uniqueid_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTempid()) {
          
          return false;
        }
        if (!hasUniqueid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Cmd.Public.stMicInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Cmd.Public.stMicInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint64 tempid = 1;
      private long tempid_ ;
      /**
       * <code>required uint64 tempid = 1;</code>
       */
      public boolean hasTempid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 tempid = 1;</code>
       */
      public long getTempid() {
        return tempid_;
      }
      /**
       * <code>required uint64 tempid = 1;</code>
       */
      public Builder setTempid(long value) {
        bitField0_ |= 0x00000001;
        tempid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 tempid = 1;</code>
       */
      public Builder clearTempid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tempid_ = 0L;
        onChanged();
        return this;
      }

      // required string uniqueid = 2;
      private java.lang.Object uniqueid_ = "";
      /**
       * <code>required string uniqueid = 2;</code>
       */
      public boolean hasUniqueid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string uniqueid = 2;</code>
       */
      public java.lang.String getUniqueid() {
        java.lang.Object ref = uniqueid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uniqueid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string uniqueid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUniqueidBytes() {
        java.lang.Object ref = uniqueid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uniqueid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string uniqueid = 2;</code>
       */
      public Builder setUniqueid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uniqueid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string uniqueid = 2;</code>
       */
      public Builder clearUniqueid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uniqueid_ = getDefaultInstance().getUniqueid();
        onChanged();
        return this;
      }
      /**
       * <code>required string uniqueid = 2;</code>
       */
      public Builder setUniqueidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uniqueid_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Cmd.stMicInfo)
    }

    static {
      defaultInstance = new stMicInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Cmd.stMicInfo)
  }

  public interface stRoomUserInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint64 tempid = 1;
    /**
     * <code>required uint64 tempid = 1;</code>
     */
    boolean hasTempid();
    /**
     * <code>required uint64 tempid = 1;</code>
     */
    long getTempid();

    // required string uniqueid = 2;
    /**
     * <code>required string uniqueid = 2;</code>
     */
    boolean hasUniqueid();
    /**
     * <code>required string uniqueid = 2;</code>
     */
    java.lang.String getUniqueid();
    /**
     * <code>required string uniqueid = 2;</code>
     */
    com.google.protobuf.ByteString
        getUniqueidBytes();
  }
  /**
   * Protobuf type {@code Cmd.stRoomUserInfo}
   *
   * <pre>
   *&#47; 房间用户信息
   * </pre>
   */
  public static final class stRoomUserInfo extends
      com.google.protobuf.GeneratedMessage
      implements stRoomUserInfoOrBuilder {
    // Use stRoomUserInfo.newBuilder() to construct.
    private stRoomUserInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private stRoomUserInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final stRoomUserInfo defaultInstance;
    public static stRoomUserInfo getDefaultInstance() {
      return defaultInstance;
    }

    public stRoomUserInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private stRoomUserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              tempid_ = input.readUInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              uniqueid_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Cmd.Public.internal_static_Cmd_stRoomUserInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Cmd.Public.internal_static_Cmd_stRoomUserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Cmd.Public.stRoomUserInfo.class, Cmd.Public.stRoomUserInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<stRoomUserInfo> PARSER =
        new com.google.protobuf.AbstractParser<stRoomUserInfo>() {
      public stRoomUserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new stRoomUserInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<stRoomUserInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint64 tempid = 1;
    public static final int TEMPID_FIELD_NUMBER = 1;
    private long tempid_;
    /**
     * <code>required uint64 tempid = 1;</code>
     */
    public boolean hasTempid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 tempid = 1;</code>
     */
    public long getTempid() {
      return tempid_;
    }

    // required string uniqueid = 2;
    public static final int UNIQUEID_FIELD_NUMBER = 2;
    private java.lang.Object uniqueid_;
    /**
     * <code>required string uniqueid = 2;</code>
     */
    public boolean hasUniqueid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string uniqueid = 2;</code>
     */
    public java.lang.String getUniqueid() {
      java.lang.Object ref = uniqueid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uniqueid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string uniqueid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUniqueidBytes() {
      java.lang.Object ref = uniqueid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uniqueid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      tempid_ = 0L;
      uniqueid_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTempid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUniqueid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, tempid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUniqueidBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, tempid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUniqueidBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Cmd.Public.stRoomUserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cmd.Public.stRoomUserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cmd.Public.stRoomUserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cmd.Public.stRoomUserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cmd.Public.stRoomUserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Cmd.Public.stRoomUserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Cmd.Public.stRoomUserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Cmd.Public.stRoomUserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Cmd.Public.stRoomUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Cmd.Public.stRoomUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Cmd.Public.stRoomUserInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Cmd.stRoomUserInfo}
     *
     * <pre>
     *&#47; 房间用户信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Cmd.Public.stRoomUserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Cmd.Public.internal_static_Cmd_stRoomUserInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Cmd.Public.internal_static_Cmd_stRoomUserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Cmd.Public.stRoomUserInfo.class, Cmd.Public.stRoomUserInfo.Builder.class);
      }

      // Construct using Cmd.Public.stRoomUserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        tempid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        uniqueid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Cmd.Public.internal_static_Cmd_stRoomUserInfo_descriptor;
      }

      public Cmd.Public.stRoomUserInfo getDefaultInstanceForType() {
        return Cmd.Public.stRoomUserInfo.getDefaultInstance();
      }

      public Cmd.Public.stRoomUserInfo build() {
        Cmd.Public.stRoomUserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Cmd.Public.stRoomUserInfo buildPartial() {
        Cmd.Public.stRoomUserInfo result = new Cmd.Public.stRoomUserInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tempid_ = tempid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uniqueid_ = uniqueid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Cmd.Public.stRoomUserInfo) {
          return mergeFrom((Cmd.Public.stRoomUserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Cmd.Public.stRoomUserInfo other) {
        if (other == Cmd.Public.stRoomUserInfo.getDefaultInstance()) return this;
        if (other.hasTempid()) {
          setTempid(other.getTempid());
        }
        if (other.hasUniqueid()) {
          bitField0_ |= 0x00000002;
          uniqueid_ = other.uniqueid_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTempid()) {
          
          return false;
        }
        if (!hasUniqueid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Cmd.Public.stRoomUserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Cmd.Public.stRoomUserInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint64 tempid = 1;
      private long tempid_ ;
      /**
       * <code>required uint64 tempid = 1;</code>
       */
      public boolean hasTempid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 tempid = 1;</code>
       */
      public long getTempid() {
        return tempid_;
      }
      /**
       * <code>required uint64 tempid = 1;</code>
       */
      public Builder setTempid(long value) {
        bitField0_ |= 0x00000001;
        tempid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 tempid = 1;</code>
       */
      public Builder clearTempid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tempid_ = 0L;
        onChanged();
        return this;
      }

      // required string uniqueid = 2;
      private java.lang.Object uniqueid_ = "";
      /**
       * <code>required string uniqueid = 2;</code>
       */
      public boolean hasUniqueid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string uniqueid = 2;</code>
       */
      public java.lang.String getUniqueid() {
        java.lang.Object ref = uniqueid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uniqueid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string uniqueid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUniqueidBytes() {
        java.lang.Object ref = uniqueid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uniqueid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string uniqueid = 2;</code>
       */
      public Builder setUniqueid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uniqueid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string uniqueid = 2;</code>
       */
      public Builder clearUniqueid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uniqueid_ = getDefaultInstance().getUniqueid();
        onChanged();
        return this;
      }
      /**
       * <code>required string uniqueid = 2;</code>
       */
      public Builder setUniqueidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uniqueid_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Cmd.stRoomUserInfo)
    }

    static {
      defaultInstance = new stRoomUserInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Cmd.stRoomUserInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Cmd_stRoomInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Cmd_stRoomInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Cmd_stVoiceUserInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Cmd_stVoiceUserInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Cmd_stMicInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Cmd_stMicInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Cmd_stRoomUserInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Cmd_stRoomUserInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014public.proto\022\003Cmd\"L\n\nstRoomInfo\022\016\n\006roo" +
      "mid\030\001 \002(\004\022!\n\010roomtype\030\002 \002(\0162\017.Cmd.enRoom" +
      "Type\022\013\n\003num\030\003 \002(\r\"\035\n\017stVoiceUserInfo\022\n\n\002" +
      "id\030\001 \002(\004\"-\n\tstMicInfo\022\016\n\006tempid\030\001 \002(\004\022\020\n" +
      "\010uniqueid\030\002 \002(\t\"2\n\016stRoomUserInfo\022\016\n\006tem" +
      "pid\030\001 \002(\004\022\020\n\010uniqueid\030\002 \002(\t*\202\001\n\nenRoomTy" +
      "pe\022\021\n\rROOM_TYPE_MIN\020\000\022\023\n\017ROOM_TYPE_QUEUE" +
      "\020\001\022\022\n\016ROOM_TYPE_FREE\020\002\022\021\n\rROOM_TYPE_TWO\020" +
      "\003\022\022\n\016ROOM_TYPE_ONLY\020\004\022\021\n\rROOM_TYPE_MAX\020\005" +
      "*j\n\014enRoomReason\022\023\n\017ROOM_REASON_MIN\020\000\022\026\n",
      "\022ROOM_REASON_NORMAL\020\001\022\030\n\024ROOM_REASON_RAN" +
      "DCHAT\020\002\022\023\n\017ROOM_REASON_MAX\020\003*\222\004\n\007enCmdId" +
      "\022\n\n\006enNone\020\000\022\026\n\022enRequestLogicInfo\020\001\022\025\n\021" +
      "enNotifyLogicInfo\020\002\022\022\n\016enRequestLogin\020\003\022" +
      "\027\n\023enNotifyLoginResult\020\004\022\027\n\023enRequestCre" +
      "ateRoom\020\005\022\030\n\024enNotifyCreateResult\020\006\022\026\n\022e" +
      "nRequestEnterRoom\020\007\022\027\n\023enNotifyEnterResu" +
      "lt\020\010\022\025\n\021enRequestRoomList\020\t\022\024\n\020enNotifyR" +
      "oomList\020\n\022\030\n\024enNotifyAddVoiceUser\020\013\022\031\n\025e" +
      "nRequestJoinMicQueue\020\014\022\032\n\026enRequestLeave",
      "MicQueue\020\r\022\024\n\020enNotifyMicQueue\020\016\022\023\n\017enNo" +
      "tifyTakeMic\020\017\022\026\n\022enRequestLeaveRoom\020\020\022\030\n" +
      "\024enNotifyDelVoiceUser\020\021\022\031\n\025enNotifySomeE" +
      "nterRoom\020\022\022\024\n\020enNotifyRandChat\020\025\022\024\n\020enRe" +
      "turnRandChat\020\026\022\031\n\025enNotifySomeLeaveRoom\020" +
      "\023"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Cmd_stRoomInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Cmd_stRoomInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Cmd_stRoomInfo_descriptor,
              new java.lang.String[] { "Roomid", "Roomtype", "Num", });
          internal_static_Cmd_stVoiceUserInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Cmd_stVoiceUserInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Cmd_stVoiceUserInfo_descriptor,
              new java.lang.String[] { "Id", });
          internal_static_Cmd_stMicInfo_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Cmd_stMicInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Cmd_stMicInfo_descriptor,
              new java.lang.String[] { "Tempid", "Uniqueid", });
          internal_static_Cmd_stRoomUserInfo_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_Cmd_stRoomUserInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Cmd_stRoomUserInfo_descriptor,
              new java.lang.String[] { "Tempid", "Uniqueid", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
